<?php
$bf1942 = '"bf1942.exe"';
$bf2 = '"bf2.exe"';
$ut2004 = '"C:\Program Files (x86)\Steam\steamapps\common\Unreal Tournament 2004\System\UT2004.exe"';
$quake3 = '"C:\Games\Quake III Arena\ioquake3.x86.exe"';
$quake2 = 'C:\Games\Quake2\quake2.exe';
$wc3 = '"C:\Program Files (x86)\Warcraft III\war3.exe"';
$wc3lc = '"C:\Program Files (x86)\Warcraft III\lancraft.exe"';
$cncrenegade = '"C:\Program Files (x86)\Steam\steamapps\common\Command & Conquer Renegade\Renegade.exe"';
?>